// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-I8skLrJNyLxWmH7k83XPec2NF_VIN9k',
    appId: '1:182240296350:android:7e367c2b595325cb8dea8f',
    messagingSenderId: '182240296350',
    projectId: 'weather-app-ka',
    databaseURL: 'https://weather-app-ka-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-ka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqzYE4Du9RD8l-qiyIVb2J5lZ8PMq8H4Y',
    appId: '1:182240296350:ios:d9f5779de7eca4138dea8f',
    messagingSenderId: '182240296350',
    projectId: 'weather-app-ka',
    databaseURL: 'https://weather-app-ka-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-app-ka.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );
}
